name: Zuri Company Files Deployment
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling changes for testing
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/zc_plugin_company_files
            git stash
            git fetch --all
            git reset --hard origin/dev
            git checkout dev
            git pull origin dev
            yarn build
            pm2 restart 0
            
 
